version: "3"

services:
  web:
    build: .
    container_name: "web-app-server"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
    networks:
      - postgres
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    container_name: "postgres-db-server"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgres
    env_file:
      - ./.env

  pgadmin:
    container_name: "pgadmin-django-server"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: redis
    command: redis-server
    container_name: "redis-server"
    ports:
      - "6379:6379"
    networks:
      - postgres


volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
    driver: bridge
